name: react@next integration

on:
  schedule:
    # Run every Monday at 12:00 (see https://crontab.guru)
    - cron: '0 12 * * 1'

jobs:
  react-next:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    # Install next-tagged versions
    - run: npm update react@next react-dom@next
    # Only run the unit tests
    - run: npm run unit
